"""set lazy='select' in posts field

Revision ID: 2cab6aee36e0
Revises: e9552ed517da
Create Date: 2024-12-16 22:14:57.468823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cab6aee36e0'
down_revision: Union[str, None] = 'e9552ed517da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
