"""Fourth migration

Revision ID: ae9ee4d5eeea
Revises: d90fb38ec7bc
Create Date: 2024-12-25 11:36:41.340630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae9ee4d5eeea'
down_revision: Union[str, None] = 'd90fb38ec7bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
